-- AlterTable
ALTER TABLE "Work" ADD COLUMN IF NOT EXISTS "titleEn" TEXT;
ALTER TABLE "Work" ADD COLUMN IF NOT EXISTS "descriptionEn" TEXT;
ALTER TABLE "Work" ADD COLUMN IF NOT EXISTS "contentEn" TEXT;
ALTER TABLE "Work" ADD COLUMN IF NOT EXISTS "servicesEn" TEXT;
ALTER TABLE "Work" ADD COLUMN IF NOT EXISTS "tagsEn" TEXT;
